<?php
use Drupal\Core\Entity\EntityInterface;
use GuzzleHttp\Exception\RequestException;

function gsb_data_index_entity_presave(EntityInterface $entity) {
  // Run in draft State
  if ($entity->bundle() == 'resource') {
    $moderation_state = $entity->get('moderation_state')->getValue()[0]['value'];

    // Only run api call if we are not in the draft state.
    if ($moderation_state !== 'draft') {
      $fields_to_watch = array(
        'title',
        'field_az_id',
        'field_roam_subscription_id',
        'field_redivis_id',
        'field_darc_airtable_id',
      );
      $changed_fields = gsb_data_index_get_changed_fields($entity);

      if (array_keys_exists($fields_to_watch, $changed_fields)) {
        $attributes = array(
          'dataset_id' => $entity->id(),
          'dataset_name' => $entity->label(),
          'az_id' => $entity->get('field_az_id')->value,
          'roam_id' => $entity->get('field_roam_subscription_id')->value,
          'redivis_id' => $entity->get('field_redivis_id')->value,
          'darc_id' => $entity->get('field_darc_airtable_id')->value
        );

        $response = gsb_data_index_snaplogic_api_call('POST', 'rh-dataindex/updateDataset', $attributes);
      }

      $integration_fields = array(
        'field_az_id',
        'field_roam_subscription_id',
        'field_redivis_id',
        'field_darc_airtable_id',
      );

      if (array_keys_exists($integration_fields, $changed_fields)) {
        $response = gsb_data_index_snaplogic_api_call('GET', 'rh-dataindex/getDatasets?dataset_index_id=' . $entity->id());
        $results = json_decode($response['body'], true);
        if (!empty($results)) {
          $results = $results[0];

          // A2Z Data
          $entity->set('field_a_z_description', $results['a2z_abstract']);
          $entity->set('field_a_z_internal_note', $results['a2z_internal_note']);
          $entity->set('field_a_z_list_url', $results['a2z_url']);
          $entity->set('field_a_z_internal_note', $results['a2z_internal_note']);
          $az_visibility = ($results['a2z_visibility']) ? 'yes' : 'no';
          $entity->set('field_visible_in_a_z', $az_visibility);

          $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
          $term_ids = [];

          foreach (explode('|', $results['a2z_topics']) as $topic) {
            $terms = $term_storage->loadByProperties([
              'name' => $topic,
              'vid' => 'topics',
            ]);

            if (!empty($terms)) {
              $term = reset($terms);
              $term_ids[] = $term->id();
            }
          }

          $entity->set('field_topics', $term_ids);

          // Redivis Data
          $entity->set('field_redivis_current_version', $results['redivis_current_version']);
          $entity->set('field_redivis_methodology', $results['redivis_methodology']);
          $entity->set('field_redivis_pub_access_level', $results['redivis_public_access_level']);
          $entity->set('field_redivis_released_date', explode('.', $results['redivis_release_date'])[0]);
          $entity->set('field_redivis_updated_date', explode('.', $results['redivis_version_updated_date'])[0]);
          $entity->set('field_redivis_url', $results['redivis_url']);


          $bbox_value = '';
          if (!empty($results['redivis_geoBBox_west_longitude'])) {
            $bbox_top = $results['redivis_geoBBox_north_latitude'];
            $bbox_left = $results['redivis_geoBBox_west_longitude'];
            $bbox_bottom = $results['redivis_geoBBox_south_latitude'];
            $bbox_right = $results['redivis_geoBBox_east_longitude'];

            $bbox_value = 'POLYGON((' . $bbox_right . ' ' . $bbox_top . ', ' . $bbox_right . ' ' . $bbox_bottom . ', ' . $bbox_left . ' ' . $bbox_bottom . ', ' . $bbox_left . ' ' . $bbox_top . ', ' . $bbox_right . ' ' . $bbox_top . '))';
          }
          $entity->set('field_bbox', $bbox_value);

          // Roam Data
          $entity->set('field_roam_publisher_identifier', $results['roam_publisher_id']);
          $entity->set('field_publisher', $results['roam_publisher_names']);
          $entity->set('field_roam_license_id', $results['roam_license_id']);
          $entity->set('field_license_name', $results['roam_license_name']);

          // DARC Data
          $entity->set('field_darc_notes', $results['darc_data_description']);
        }
      }
    }
  }
  return;
}

function gsb_data_index_get_changed_fields($entity) {
  $changed_fields = array();
  if ($entity->isNew()) {
    $changed_fields['is_new'] = true;
    foreach($entity->getFields() as $field_name => $field) {
      $field_type = $field->getFieldDefinition()->getType();
      $new_value = '';
      switch ($field_type) {
        case 'entity_reference':
          if (!$entity->get($field_name)->isEmpty()) {
            $new_value = (!$entity->get($field_name)->isEmpty()) ? $entity->get($field_name)->entity->label() : '';
          }
          break;

        case 'boolean':
          $new_value = filter_var($entity->get($field_name)->value, FILTER_VALIDATE_BOOLEAN);
          break;

        default:
          $new_value = $entity->get($field_name)->value;
      }

      $changed_fields[$field_name] = [
        'original' => NULL,
        'new' => $new_value,
        'field_type' => $field_type,
      ];
    }
  }
  else {
    $changed_fields['is_new'] = false;

    $original = $entity->original;

    foreach($entity->getFields() as $field_name => $field) {
      $field_type = $field->getFieldDefinition()->getType();
      $original_value = '';
      $new_value = '';
      switch($field_type) {
        case 'entity_reference':

          if (!$original->get($field_name)->isEmpty()) {
            $original_value = (!$original->get($field_name)->isEmpty()) ? $original->get($field_name)->entity->label() : '';
            $new_value = (!$entity->get($field_name)->isEmpty()) ? $entity->get($field_name)->entity->label() : '';
          }
          break;

        case 'boolean':
          $original_value = filter_var($original->get($field_name)->value, FILTER_VALIDATE_BOOLEAN);
          $new_value = filter_var($entity->get($field_name)->value, FILTER_VALIDATE_BOOLEAN);
          break;

        default:
          $original_value = $original->get($field_name)->value;
          $new_value = $entity->get($field_name)->value;
      }

      if ($original_value !== $new_value) {
        $changed_fields[$field_name] = array(
          'original' => $original_value,
          'new' => $new_value,
          'field_type' => $field_type,
        );
      }
    }
  }

  return $changed_fields;
}

function array_keys_exists(array $keys, array $array) {
  $diff = array_diff_key(array_flip($keys), $array);
  return count($diff) !== count($keys);
}
/**
 * Makes a REST POST request to SnapLogic API.
 */
function gsb_data_index_snaplogic_api_call($method, $endpoint, $data = null) {
  // Get the SnapLogic settings from config.
  $config = \Drupal::config('gsb_data_index.settings');
  $environment = $config->get('snaplogic_environment');
  $api_token = $config->get('snaplogic_api_token');

  // Ensure the API token is available.
  if (!$api_token) {
    \Drupal::logger('gsb_data_index')->error('SnapLogic API token is missing.');
    return;
  }

  // Define the endpoint URL.
  $url = 'https://elastic.snaplogic.com/api/1/rest/slsched/feed/' . $environment . '/GSB/' . $endpoint;

  // Define the headers.
  $headers = [
    'Authorization' => 'Bearer ' . $api_token,
    'Content-Type' => 'application/json',
  ];

  try {
    switch($method) {
      case 'POST':
        // Convert data array to JSON.
        $body = json_encode($data);

        // Make the POST request.
        $response = \Drupal::httpClient()->post($url, [
          'headers' => $headers,
          'body' => $body,
        ]);
        break;

      case 'GET':
        $response = \Drupal::httpClient()->get($url, [
          'headers' => $headers,
        ]);
        break;
    }

    // Get response status and body.
    $status_code = $response->getStatusCode();
    $response_body = $response->getBody()->getContents();

    // Log the response.
    \Drupal::logger('my_module')->notice('SnapLogic API Response: ' . $response_body);

    return [
      'status' => $status_code,
      'body' => $response_body,
    ];
  } catch (RequestException $e) {
    // Log errors.
    \Drupal::logger('gsb_data_index')->error('SnapLogic API Error: ' . $e->getMessage());
    return NULL;
  }
}

